### ISSUE TITLE
load a weight file containing 77 layers into a model with 78 layers.

### ISSUE THREAD

**Issue by Lynn0306** [tuvovan/NHDRRNet#10]
Hi, I encounter a problem when loading the weights of NNHDRNet.h5. It appears an error 'ValueError: You are trying to load a weight file containing 77 layers into a model with 78 layers.' 

Can anyone help me?

**Comment by tuvovan** [comment]
the weight file was broken and I didn't have time to retrain it. Please pull the code and train from the beginning. Thanks!

**Comment by Lynn0306** [comment]
Okay! Thanks!
