### ISSUE TITLE
Lỗi Tensorflow_addons

### ISSUE THREAD

**Issue by Chinhpy** [tuvovan/NHDRRNet#2]
Bạn ơi mình có thử lấy code bạn bỏ lên Google colab để chạy thử. Nhưng bị lỗi ở dòng from tensorflow_addons.layers import AdaptiveAveragePooling2D.
Không biết bạn cài Tensorflow_addons phiên bản nào ?

**Comment by tuvovan** [comment]
mình dùng 0.11.2 b nhé.

**Comment by Chinhpy** [comment]
dạ em cảm ơn nhiều! cái này hay quá anh ơi có gì cho em hỏi thêm nha anh.


Vào CN, 1 thg 11, 2020 vào lúc 16:22 Vo Van Tu <notifications@github.com>
đã viết:

**Comment by tuvovan** [comment]
bạn cần gì cứ email mình nhé. mình có đính kèm trong file readme rồi nha ^^

**Comment by Chinhpy** [comment]
bạn ơi cho mình hỏi là code NHDRRNet training trên GPU vậy card đồ họa đủ
để train là card nào vậy bạn.
bạn sử dụng card nào để training vậy.
mình cảm ơn!


Vào Th 2, 2 thg 11, 2020 vào lúc 08:43 Vo Van Tu <notifications@github.com>
đã viết:

**Comment by tuvovan** [comment]
mình dùng Tesla-V100 b ạ.

**Comment by Chinhpy** [comment]
Thanks ban nhieu!

Vào 09:59, T.3, 3 Th11, 2020 Vo Van Tu <notifications@github.com> đã viết:

**Comment by Chinhpy** [comment]
anh ơi! cho em hỏi khi em chạy code create_dataset mà bị lỗi như trong hình
là do đâu vậy anh?
em check đường dẫn đúng hết rồi. mong được anh trả lời sớm em cảm ơn

Vào Th 3, 3 thg 11, 2020 vào lúc 13:04 Nguyễn Trường Chinh Tôn <
tntchinh.suc1201@gmail.com> đã viết:
