### ISSUE TITLE
lỗi reshape array

### ISSUE THREAD

**Issue by Chinhpy** [tuvovan/NHDRRNet#3]
![Untitled](https://user-images.githubusercontent.com/73774920/101244845-509d0d00-373b-11eb-86a9-673dd8ab7227.png)
Bạn ơi cho mình hỏi là khi mình chạy xong code create_dataset thì mình nhận được file trainning/data_01 16gb rồi sau  đó mình chạy code main.py thì bị lỗi "ValueError: cannot reshape array of size 2147483648 into shape (1184,4,512,512,6)" như trong hình.
bạn có thể giải thích giúp mình với được không?

**Comment by tuvovan** [comment]
b đã tạo dataset chưa vậy?

**Comment by Chinhpy** [comment]
![Untitled](https://user-images.githubusercontent.com/73774920/101270482-0dc74d80-37ac-11eb-9fdf-de580cee2fc2.png)
 bạn có thể xem lại giúp mình code với được k? mình bị lỗi k defined DCE

**Comment by tuvovan** [comment]
mình có update rồi, b xóa bản cũ, kéo lại code mình mới update nha

**Comment by Chinhpy** [comment]
![Untitled](https://user-images.githubusercontent.com/73774920/101271566-70bde200-37b6-11eb-9d53-cafad9a3d2ba.png)
bạn ơi sau khi mình updata lại code thì chạy lúc bắt đầu trainning thì gặp lỗi này. bạn có thể cho mình hỏi là vì sao bị lỗi này được không?

**Comment by tuvovan** [comment]
b kéo lại và thử lại nhé. cẩn thận với mấy cái libraries nhé. goodluck!

**Comment by Chinhpy** [comment]
![image](https://user-images.githubusercontent.com/73774920/101312798-438d3480-3887-11eb-8b1e-b8f11b9ae4c4.png)
Mình cảm ơn B nhiều!
ban ơi! mình train thử 80 epoch đầu vì máy mình hơi yếu, train xong mình có dùng file test để thử và bị lí do này. này lo do mình train quá ít hay là do lỗi code vậy a?

**Comment by tuvovan** [comment]
b có thể comment out 2 dòng 62 và 63 nhé

**Comment by Chinhpy** [comment]
mình chạy được rồi cảm ơn bạn nhiều  hình như là comment out dòng 65 nữa thì phải bạn ơi! và size ảnh trong file test đổi lại 512 hết đúng k bạn

**Comment by tuvovan** [comment]
dòng 65 m sửa lại rồi nhé, cái đó dùng trong trường hợp b có 2 GPU và muốn test kết quả lúc bạn đang training thôi. nếu b chỉ có 1 gpu thì b bỏ đi cũng được.

khi test k nhất thiết phải sửa thành 512 nhé, ở dòng 27 mình đã sửa rồi. b có thể resize nhỏ hơn nếu như GPU của b k đủ bộ nhớ.

Chúc may mắn nhé!

**Comment by Chinhpy** [comment]
Mình cảm ơn bạn rất nhiều! code chạy ổn rồi nhưng mà mấy mình yêu quá train 200 epoch mà tốn hết 1 ngày rưỡi. 
bạn có thể cho mình xin trọng số trainning(Weights) của best.h5 của bạn được k?

**Comment by tuvovan** [comment]
file đó mình có dẫn link rồi, b đọc kĩ file readme nhé. trong đó mình ghi đầy đủ rồi đấy.

**Comment by tuvovan** [comment]
với cả file đó vẫn cần phải train thêm b nhé, mình cũng mới train có mấy epoch thôi.

**Comment by Chinhpy** [comment]
thanks u so much!  mình thầy rồi nha.

**Comment by tuvovan** [comment]
nếu thấy có ích thì để lại cho m 1 sao nhé ^^

**Comment by Chinhpy** [comment]
chào bạn! desktop mình đang dùng car màn hình nvidia geforce rtx 2070 super mình train code này 500 epoch mà tận 3 ngày mới xong nhưng kết quả ra rất tệ tại vì default của code này yêu cầu tận 160000 epoch. bạn ơi có cách nào để tăng tốc độ train không? máy mình yêu quá thì giờ mình muốn thuê sever train thì ổn không ban? bạn có thể cho mình xin vài ý kiến được không? 
cảm ơn bạn nhiều! 
à mà cái weight mình tải của bạn hình như cũng mới train tầm 100 epoch kết quả cũng thấp.
