### ISSUE TITLE
train-model

### ISSUE THREAD

**Issue by Chinhpy** [tuvovan/NHDRRNet#4]
chào bạn! desktop mình đang dùng car màn hình nvidia geforce rtx 2070 super mình train code này 500 epoch mà tận 3 ngày mới xong nhưng kết quả ra rất tệ tại vì default của code này yêu cầu tận 160000 epoch. bạn ơi có cách nào để tăng tốc độ train không? máy mình train k nổi  thì giờ mình muốn thuê sever train thì ổn không bạn? bạn có thể cho mình xin vài ý kiến được không?
cảm ơn bạn nhiều!
à mà cái weight mình tải của bạn hình như cũng mới train tầm 100 epoch kết quả cũng thấp.

**Comment by tuvovan** [comment]
Cái này không thuộc về vấn đề code nên mình không giúp được b nha.
