### ISSUE TITLE
kết quả sau khi training

### ISSUE THREAD

**Issue by Chinhpy** [tuvovan/NHDRRNet#7]
chào bạn!
cho mình hỏi là code của bạn có vấn đề không sao mình training tới min loss còn rất thấp(minh nghĩ nó đã convergence) nhưng kết quả lại rất tệ.
![hdr](https://user-images.githubusercontent.com/73774920/104680137-c8d6f500-5721-11eb-8133-61c7abfcfa02.jpg)

**Comment by Chinhpy** [comment]
![image](https://user-images.githubusercontent.com/73774920/104683360-5702a980-5729-11eb-8ab7-0f5058ab5468.png)
hình như cái hàm này của bạn có vấn đề làm cho bức hình nó bị màu xanh như vậy đúng k?

**Comment by tuvovan** [comment]
b thu convert rbg sang bgr truoc ham cv2.imwrite di.
